name: version_bump

permissions:
  contents: write
  pull-requests: write
  id-token: write

on: workflow_dispatch

jobs:
  build:
    name: version bump
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: canary

      - name: Set up Git identity
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Bump version
        run: |
          deno run -A jsr:@deno/bump-workspaces@^0.1/cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_USER_NAME: ${{ github.actor }}
          GIT_USER_EMAIL: ${{ github.actor}}@users.noreply.github.com

      - name: Read version from deno.jsonc
        id: version
        run: echo "version=v$(jq -r .version deno.jsonc)" >> $GITHUB_OUTPUT

      - name: Commit, Tag, and Push
        run: |
          git add .
          git commit -m "chore: bump version"
          git tag ${{ steps.version.outputs.version }}
          git push origin HEAD --follow-tags

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.version.outputs.version }}" --generate-notes --verify-tag
